name: Discord Member Monitor

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minute
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install requests
      - name: Run monitor script
        run: python monitor_user_token.py
